spring:
  application:
    name: athlete-performance-tracker
  
  datasource:
    url: jdbc:postgresql://localhost:5432/athlete_tracker
    username: ${DB_USERNAME:at}
    password: ${DB_PASSWORD:at}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

server:
  port: 8081
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.athletetracker: DEBUG
    org.springframework.security: DEBUG

  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: "*"

app:
  jwt:
    secret: ${JWT_SECRET:MyVerySecureJwtSecretKeyForAthletePerformanceTrackerThatIs256BitsLongForHS256Algorithm}
    expiration: 86400000 # 24 hours
    refresh-expiration: 604800000 # 7 days
  
  oauth2:
    issuer-uri: ${OAUTH2_ISSUER_URI:http://localhost:8081}
    default-redirect-uri: ${OAUTH2_DEFAULT_REDIRECT_URI:http://localhost:3001/auth/callback}
    access-token-validity: ${OAUTH2_ACCESS_TOKEN_VALIDITY:PT15M} # 15 minutes
    refresh-token-validity: ${OAUTH2_REFRESH_TOKEN_VALIDITY:PT1H} # 1 hour
    frontend-login-url: ${OAUTH2_FRONTEND_LOGIN_URL:http://localhost:3001/oauth2/login}
  
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3001}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
  
  email:
    enabled: ${EMAIL_ENABLED:false}
    from-address: ${EMAIL_FROM_ADDRESS:noreply@athletetracker.com}
    from-name: ${EMAIL_FROM_NAME:Athlete Performance Tracker}
    frontend-url: ${EMAIL_FRONTEND_URL:http://localhost:3001}
    template-path: classpath:/templates/email/