-- Create coaches table following the same pattern as athletes table
CREATE TABLE coaches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(20),
    office_location VARCHAR(200),
    years_experience INTEGER,
    certifications TEXT,
    specializations VARCHAR(500),
    coaching_philosophy TEXT,
    preferred_sports VARCHAR(500),
    preferred_contact_method VARCHAR(50),
    availability_hours VARCHAR(200),
    bio TEXT,
    profile_photo_url VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT UNIQUE
);

-- Create indexes for common queries
CREATE INDEX idx_coaches_user_id ON coaches(user_id);
CREATE INDEX idx_coaches_active ON coaches(is_active);
CREATE INDEX idx_coaches_name ON coaches(first_name, last_name);